#  source: https://stacksecrets.com/dot-net-core/connect-net-core-with-postgresql-on-a-docker-container

version: '3'

services:
  db:
    image: postgres:11.2
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - pgconf:/etc/postgresql
      - pglog:/var/log/postgresql
    environment:
      - POSTGRES_DB=red_tech
      - POSTGRES_USER=red_user
      - POSTGRES_PASSWORD=red_password

volumes:
  pgdata:
    driver: local
  pgconf:
    driver: local
  pglog:
    driver: local